// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCloudprovidersTbl = "cloudproviders_tbl"

// CloudprovidersTbl mapped from table <cloudproviders_tbl>
type CloudprovidersTbl struct {
	CreatedAt          time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion      int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted            bool           `gorm:"column:deleted;not null" json:"deleted"`
	ID                 string         `gorm:"column:id;primaryKey" json:"id"`
	Description        string         `gorm:"column:description" json:"description"`
	IsEmulated         bool           `gorm:"column:is_emulated;not null" json:"is_emulated"`
	Name               string         `gorm:"column:name;not null" json:"name"`
	Status             string         `gorm:"column:status;not null;default:init" json:"status"`
	Progress           float32        `gorm:"column:progress;default:100" json:"progress"`
	Enabled            bool           `gorm:"column:enabled" json:"enabled"`
	DomainID           string         `gorm:"column:domain_id;not null;default:default" json:"domain_id"`
	TenantID           string         `gorm:"column:tenant_id;not null" json:"tenant_id"`
	ExternalID         string         `gorm:"column:external_id" json:"external_id"`
	ImportedAt         time.Time      `gorm:"column:imported_at" json:"imported_at"`
	Source             string         `gorm:"column:source" json:"source"`
	SyncStatus         string         `gorm:"column:sync_status;default:idle" json:"sync_status"`
	LastSync           time.Time      `gorm:"column:last_sync" json:"last_sync"`
	LastSyncEndAt      time.Time      `gorm:"column:last_sync_end_at" json:"last_sync_end_at"`
	HealthStatus       string         `gorm:"column:health_status;not null;default:normal" json:"health_status"`
	AccessURL          string         `gorm:"column:access_url" json:"access_url"`
	Account            string         `gorm:"column:account;not null" json:"account"`
	Secret             string         `gorm:"column:secret;not null" json:"secret"`
	CloudaccountID     string         `gorm:"column:cloudaccount_id;not null" json:"cloudaccount_id"`
	Provider           string         `gorm:"column:provider" json:"provider"`
	ProjectSrc         string         `gorm:"column:project_src;not null;default:cloud" json:"project_src"`
	ProjectMappingID   string         `gorm:"column:project_mapping_id" json:"project_mapping_id"`
	EnableProjectSync  bool           `gorm:"column:enable_project_sync" json:"enable_project_sync"`
	EnableResourceSync bool           `gorm:"column:enable_resource_sync;default:1" json:"enable_resource_sync"`
}

// TableName CloudprovidersTbl's table name
func (*CloudprovidersTbl) TableName() string {
	return TableNameCloudprovidersTbl
}
