// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCloudaccountsTbl = "cloudaccounts_tbl"

// CloudaccountsTbl mapped from table <cloudaccounts_tbl>
type CloudaccountsTbl struct {
	CreatedAt                    time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt                    time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion                int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt                    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted                      bool           `gorm:"column:deleted;not null" json:"deleted"`
	ID                           string         `gorm:"column:id;primaryKey" json:"id"`
	Description                  string         `gorm:"column:description" json:"description"`
	IsEmulated                   bool           `gorm:"column:is_emulated;not null" json:"is_emulated"`
	Name                         string         `gorm:"column:name;not null" json:"name"`
	DomainID                     string         `gorm:"column:domain_id;not null;default:default" json:"domain_id"`
	DomainSrc                    string         `gorm:"column:domain_src" json:"domain_src"`
	IsPublic                     bool           `gorm:"column:is_public;not null" json:"is_public"`
	PublicScope                  string         `gorm:"column:public_scope;not null;default:system" json:"public_scope"`
	PublicSrc                    string         `gorm:"column:public_src" json:"public_src"`
	Status                       string         `gorm:"column:status;not null;default:init" json:"status"`
	Progress                     float32        `gorm:"column:progress;default:100" json:"progress"`
	Enabled                      bool           `gorm:"column:enabled" json:"enabled"`
	SyncStatus                   string         `gorm:"column:sync_status;default:idle" json:"sync_status"`
	LastSync                     time.Time      `gorm:"column:last_sync" json:"last_sync"`
	LastSyncEndAt                time.Time      `gorm:"column:last_sync_end_at" json:"last_sync_end_at"`
	TenantID                     string         `gorm:"column:tenant_id" json:"tenant_id"`
	AccessURL                    string         `gorm:"column:access_url" json:"access_url"`
	Account                      string         `gorm:"column:account;not null" json:"account"`
	Secret                       string         `gorm:"column:secret;not null" json:"secret"`
	AccountID                    string         `gorm:"column:account_id" json:"account_id"`
	IsPublicCloud                bool           `gorm:"column:is_public_cloud;default:1" json:"is_public_cloud"`
	IsOnPremise                  bool           `gorm:"column:is_on_premise;not null" json:"is_on_premise"`
	Provider                     string         `gorm:"column:provider" json:"provider"`
	Balance                      float64        `gorm:"column:balance" json:"balance"`
	Currency                     string         `gorm:"column:currency;not null" json:"currency"`
	ProbeAt                      time.Time      `gorm:"column:probe_at" json:"probe_at"`
	HealthStatus                 string         `gorm:"column:health_status;not null;default:normal" json:"health_status"`
	ErrorCount                   int32          `gorm:"column:error_count" json:"error_count"`
	AutoCreateProject            bool           `gorm:"column:auto_create_project" json:"auto_create_project"`
	AutoCreateProjectForProvider bool           `gorm:"column:auto_create_project_for_provider" json:"auto_create_project_for_provider"`
	Version                      string         `gorm:"column:version" json:"version"`
	Sysinfo                      string         `gorm:"column:sysinfo" json:"sysinfo"`
	Brand                        string         `gorm:"column:brand" json:"brand"`
	Options                      string         `gorm:"column:options" json:"options"`
	ShareMode                    string         `gorm:"column:share_mode" json:"share_mode"`
	ProxySettingID               string         `gorm:"column:proxy_setting_id;not null;default:DIRECT" json:"proxy_setting_id"`
	IamLoginURL                  string         `gorm:"column:iam_login_url;not null" json:"iam_login_url"`
	SamlAuth                     bool           `gorm:"column:saml_auth" json:"saml_auth"`
	ProjectMappingID             string         `gorm:"column:project_mapping_id" json:"project_mapping_id"`
	EnableProjectSync            bool           `gorm:"column:enable_project_sync" json:"enable_project_sync"`
	EnableResourceSync           bool           `gorm:"column:enable_resource_sync;default:1" json:"enable_resource_sync"`
	ReadOnly                     bool           `gorm:"column:read_only" json:"read_only"`
	SubAccounts                  string         `gorm:"column:sub_accounts" json:"sub_accounts"`
	LakeOfPermissions            string         `gorm:"column:lake_of_permissions" json:"lake_of_permissions"`
	SkipSyncResources            string         `gorm:"column:skip_sync_resources" json:"skip_sync_resources"`
}

// TableName CloudaccountsTbl's table name
func (*CloudaccountsTbl) TableName() string {
	return TableNameCloudaccountsTbl
}
