// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCloudProviderRegionsTbl = "cloud_provider_regions_tbl"

// CloudProviderRegionsTbl mapped from table <cloud_provider_regions_tbl>
type CloudProviderRegionsTbl struct {
	CreatedAt       time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion   int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted         bool           `gorm:"column:deleted;not null" json:"deleted"`
	RowID           int64          `gorm:"column:row_id;primaryKey;autoIncrement:true" json:"row_id"`
	SyncStatus      string         `gorm:"column:sync_status;default:idle" json:"sync_status"`
	LastSync        time.Time      `gorm:"column:last_sync" json:"last_sync"`
	LastSyncEndAt   time.Time      `gorm:"column:last_sync_end_at" json:"last_sync_end_at"`
	CloudregionID   string         `gorm:"column:cloudregion_id;not null;default:default" json:"cloudregion_id"`
	CloudproviderID string         `gorm:"column:cloudprovider_id;not null" json:"cloudprovider_id"`
	Enabled         bool           `gorm:"column:enabled;not null" json:"enabled"`
	SyncResults     string         `gorm:"column:sync_results" json:"sync_results"`
	LastDeepSyncAt  time.Time      `gorm:"column:last_deep_sync_at" json:"last_deep_sync_at"`
	LastAutoSyncAt  time.Time      `gorm:"column:last_auto_sync_at" json:"last_auto_sync_at"`
}

// TableName CloudProviderRegionsTbl's table name
func (*CloudProviderRegionsTbl) TableName() string {
	return TableNameCloudProviderRegionsTbl
}
