// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGuestsTbl = "guests_tbl"

// GuestsTbl mapped from table <guests_tbl>
type GuestsTbl struct {
	CreatedAt               time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt               time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion           int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt               gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted                 bool           `gorm:"column:deleted;not null" json:"deleted"`
	ID                      string         `gorm:"column:id;primaryKey" json:"id"`
	Description             string         `gorm:"column:description" json:"description"`
	IsEmulated              bool           `gorm:"column:is_emulated;not null" json:"is_emulated"`
	Name                    string         `gorm:"column:name;not null" json:"name"`
	Status                  string         `gorm:"column:status;not null;default:init" json:"status"`
	Progress                float32        `gorm:"column:progress;default:100" json:"progress"`
	DomainID                string         `gorm:"column:domain_id;not null;default:default" json:"domain_id"`
	TenantID                string         `gorm:"column:tenant_id;not null" json:"tenant_id"`
	PendingDeletedAt        time.Time      `gorm:"column:pending_deleted_at" json:"pending_deleted_at"`
	PendingDeleted          bool           `gorm:"column:pending_deleted;not null" json:"pending_deleted"`
	ProjectSrc              string         `gorm:"column:project_src;not null" json:"project_src"`
	IsSystem                bool           `gorm:"column:is_system" json:"is_system"`
	Freezed                 bool           `gorm:"column:freezed;not null" json:"freezed"`
	ExternalID              string         `gorm:"column:external_id" json:"external_id"`
	ImportedAt              time.Time      `gorm:"column:imported_at" json:"imported_at"`
	Source                  string         `gorm:"column:source" json:"source"`
	BillingType             string         `gorm:"column:billing_type;default:postpaid" json:"billing_type"`
	ExpiredAt               time.Time      `gorm:"column:expired_at" json:"expired_at"`
	BillingCycle            string         `gorm:"column:billing_cycle" json:"billing_cycle"`
	AutoRenew               bool           `gorm:"column:auto_renew" json:"auto_renew"`
	DisableDelete           bool           `gorm:"column:disable_delete;default:1" json:"disable_delete"`
	OsArch                  string         `gorm:"column:os_arch" json:"os_arch"`
	RecordChecksum          string         `gorm:"column:record_checksum" json:"record_checksum"`
	Hostname                string         `gorm:"column:hostname" json:"hostname"`
	HostID                  string         `gorm:"column:host_id" json:"host_id"`
	EncryptKeyID            string         `gorm:"column:encrypt_key_id" json:"encrypt_key_id"`
	CPUSockets              int32          `gorm:"column:cpu_sockets;not null;default:1" json:"cpu_sockets"`
	VcpuCount               int32          `gorm:"column:vcpu_count;not null;default:1" json:"vcpu_count"`
	VmemSize                int32          `gorm:"column:vmem_size;not null" json:"vmem_size"`
	BootOrder               string         `gorm:"column:boot_order;default:cdn" json:"boot_order"`
	ShutdownBehavior        string         `gorm:"column:shutdown_behavior;default:stop" json:"shutdown_behavior"`
	ShutdownMode            string         `gorm:"column:shutdown_mode;default:keep_charging" json:"shutdown_mode"`
	KeypairID               string         `gorm:"column:keypair_id" json:"keypair_id"`
	BackupHostID            string         `gorm:"column:backup_host_id" json:"backup_host_id"`
	BackupGuestStatus       string         `gorm:"column:backup_guest_status;not null;default:init" json:"backup_guest_status"`
	ProgressMbps            float64        `gorm:"column:progress_mbps;not null" json:"progress_mbps"`
	Vga                     string         `gorm:"column:vga" json:"vga"`
	Vdi                     string         `gorm:"column:vdi" json:"vdi"`
	Machine                 string         `gorm:"column:machine" json:"machine"`
	Bios                    string         `gorm:"column:bios" json:"bios"`
	OsType                  string         `gorm:"column:os_type" json:"os_type"`
	FlavorID                string         `gorm:"column:flavor_id" json:"flavor_id"`
	SecgrpID                string         `gorm:"column:secgrp_id" json:"secgrp_id"`
	AdminSecgrpID           string         `gorm:"column:admin_secgrp_id" json:"admin_secgrp_id"`
	SrcIPCheck              bool           `gorm:"column:src_ip_check;default:1" json:"src_ip_check"`
	SrcMacCheck             bool           `gorm:"column:src_mac_check;default:1" json:"src_mac_check"`
	Hypervisor              string         `gorm:"column:hypervisor;not null;default:kvm" json:"hypervisor"`
	InstanceType            string         `gorm:"column:instance_type" json:"instance_type"`
	SshableLastState        bool           `gorm:"column:sshable_last_state" json:"sshable_last_state"`
	IsDaemon                bool           `gorm:"column:is_daemon" json:"is_daemon"`
	InternetMaxBandwidthOut int32          `gorm:"column:internet_max_bandwidth_out" json:"internet_max_bandwidth_out"`
	Throughput              int32          `gorm:"column:throughput" json:"throughput"`
	QgaStatus               string         `gorm:"column:qga_status;not null;default:unknown" json:"qga_status"`
	PowerStates             string         `gorm:"column:power_states;not null;default:unknown" json:"power_states"`
	RescueMode              bool           `gorm:"column:rescue_mode;not null" json:"rescue_mode"`
}

// TableName GuestsTbl's table name
func (*GuestsTbl) TableName() string {
	return TableNameGuestsTbl
}
