// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHostsTbl = "hosts_tbl"

// HostsTbl mapped from table <hosts_tbl>
type HostsTbl struct {
	CreatedAt          time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion      int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted            bool           `gorm:"column:deleted;not null" json:"deleted"`
	ID                 string         `gorm:"column:id;primaryKey" json:"id"`
	Description        string         `gorm:"column:description" json:"description"`
	IsEmulated         bool           `gorm:"column:is_emulated;not null" json:"is_emulated"`
	Name               string         `gorm:"column:name;not null" json:"name"`
	DomainID           string         `gorm:"column:domain_id;not null;default:default" json:"domain_id"`
	DomainSrc          string         `gorm:"column:domain_src" json:"domain_src"`
	IsPublic           bool           `gorm:"column:is_public;not null" json:"is_public"`
	PublicScope        string         `gorm:"column:public_scope;not null;default:system" json:"public_scope"`
	PublicSrc          string         `gorm:"column:public_src" json:"public_src"`
	Status             string         `gorm:"column:status;not null;default:init" json:"status"`
	Progress           float32        `gorm:"column:progress;default:100" json:"progress"`
	Enabled            bool           `gorm:"column:enabled" json:"enabled"`
	ExternalID         string         `gorm:"column:external_id" json:"external_id"`
	ImportedAt         time.Time      `gorm:"column:imported_at" json:"imported_at"`
	Source             string         `gorm:"column:source" json:"source"`
	ZoneID             string         `gorm:"column:zone_id" json:"zone_id"`
	ManagerID          string         `gorm:"column:manager_id" json:"manager_id"`
	BillingType        string         `gorm:"column:billing_type;default:postpaid" json:"billing_type"`
	ExpiredAt          time.Time      `gorm:"column:expired_at" json:"expired_at"`
	BillingCycle       string         `gorm:"column:billing_cycle" json:"billing_cycle"`
	AutoRenew          bool           `gorm:"column:auto_renew" json:"auto_renew"`
	Hostname           string         `gorm:"column:hostname" json:"hostname"`
	Rack               string         `gorm:"column:rack" json:"rack"`
	Slots              string         `gorm:"column:slots" json:"slots"`
	AccessMac          string         `gorm:"column:access_mac" json:"access_mac"`
	AccessIP           string         `gorm:"column:access_ip" json:"access_ip"`
	ManagerURI         string         `gorm:"column:manager_uri" json:"manager_uri"`
	SysInfo            string         `gorm:"column:sys_info" json:"sys_info"`
	Sn                 string         `gorm:"column:sn" json:"sn"`
	CPUCount           int32          `gorm:"column:cpu_count" json:"cpu_count"`
	NodeCount          int32          `gorm:"column:node_count" json:"node_count"`
	CPUDesc            string         `gorm:"column:cpu_desc" json:"cpu_desc"`
	CPUMhz             int32          `gorm:"column:cpu_mhz" json:"cpu_mhz"`
	CPUCache           int32          `gorm:"column:cpu_cache" json:"cpu_cache"`
	CPUReserved        int32          `gorm:"column:cpu_reserved" json:"cpu_reserved"`
	CPUCmtbound        float32        `gorm:"column:cpu_cmtbound;default:8" json:"cpu_cmtbound"`
	CPUMicrocode       string         `gorm:"column:cpu_microcode" json:"cpu_microcode"`
	CPUArchitecture    string         `gorm:"column:cpu_architecture" json:"cpu_architecture"`
	MemSize            int32          `gorm:"column:mem_size" json:"mem_size"`
	MemReserved        int32          `gorm:"column:mem_reserved" json:"mem_reserved"`
	MemCmtbound        float32        `gorm:"column:mem_cmtbound;default:1" json:"mem_cmtbound"`
	PageSizeKb         int32          `gorm:"column:page_size_kb;not null;default:4" json:"page_size_kb"`
	EnableNumaAllocate bool           `gorm:"column:enable_numa_allocate" json:"enable_numa_allocate"`
	StorageSize        int64          `gorm:"column:storage_size" json:"storage_size"`
	StorageType        string         `gorm:"column:storage_type" json:"storage_type"`
	StorageDriver      string         `gorm:"column:storage_driver" json:"storage_driver"`
	StorageInfo        string         `gorm:"column:storage_info" json:"storage_info"`
	IpmiIP             string         `gorm:"column:ipmi_ip" json:"ipmi_ip"`
	IpmiInfo           string         `gorm:"column:ipmi_info" json:"ipmi_info"`
	HostStatus         string         `gorm:"column:host_status;not null;default:offline" json:"host_status"`
	HostType           string         `gorm:"column:host_type;not null" json:"host_type"`
	Version            string         `gorm:"column:version" json:"version"`
	OvnVersion         string         `gorm:"column:ovn_version" json:"ovn_version"`
	IsBaremetal        bool           `gorm:"column:is_baremetal" json:"is_baremetal"`
	IsMaintenance      bool           `gorm:"column:is_maintenance" json:"is_maintenance"`
	LastPingAt         time.Time      `gorm:"column:last_ping_at" json:"last_ping_at"`
	EnableHealthCheck  bool           `gorm:"column:enable_health_check" json:"enable_health_check"`
	ResourceType       string         `gorm:"column:resource_type;not null;default:shared" json:"resource_type"`
	RealExternalID     string         `gorm:"column:real_external_id" json:"real_external_id"`
	IsImport           bool           `gorm:"column:is_import" json:"is_import"`
	EnablePxeBoot      bool           `gorm:"column:enable_pxe_boot;default:1" json:"enable_pxe_boot"`
	UUID               string         `gorm:"column:uuid" json:"uuid"`
	BootMode           string         `gorm:"column:boot_mode" json:"boot_mode"`
	OvnMappedIPAddr    string         `gorm:"column:ovn_mapped_ip_addr" json:"ovn_mapped_ip_addr"`
	UefiInfo           string         `gorm:"column:uefi_info" json:"uefi_info"`
}

// TableName HostsTbl's table name
func (*HostsTbl) TableName() string {
	return TableNameHostsTbl
}
