// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameJwtBlacklist = "jwt_blacklists"

// JwtBlacklist mapped from table <jwt_blacklists>
type JwtBlacklist struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Jwt       string         `gorm:"column:jwt" json:"jwt"`               // jwt
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"` // 删除时间
}

// TableName JwtBlacklist's table name
func (*JwtBlacklist) TableName() string {
	return TableNameJwtBlacklist
}
