// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLogJob = "log_jobs"

// LogJob mapped from table <log_jobs>
type LogJob struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`  // 主键id
	Name         string         `gorm:"column:name;not null" json:"name"`                   // 任务名称
	JobGroup     string         `gorm:"column:job_group;not null" json:"job_group"`         // 分组
	EntryID      int32          `gorm:"column:entry_id;not null" json:"entry_id"`           // 任务id
	InvokeTarget string         `gorm:"column:invoke_target;not null" json:"invoke_target"` // 调用方法
	LogInfo      string         `gorm:"column:log_info;not null" json:"log_info"`           // 日志信息
	Status       int32          `gorm:"column:status;not null;default:1" json:"status"`     // 1=正常 2=异常
	CreatedAt    time.Time      `gorm:"column:created_at" json:"created_at"`                // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at" json:"updated_at"`                // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                // 删除时间
}

// TableName LogJob's table name
func (*LogJob) TableName() string {
	return TableNameLogJob
}
