// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLogLogin = "log_logins"

// LogLogin mapped from table <log_logins>
type LogLogin struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`    // 主键id
	Username      string         `gorm:"column:username;not null" json:"username"`             // 用户名
	Status        int32          `gorm:"column:status;not null;default:1" json:"status"`       // 1=正常 2=异常
	Ipaddr        string         `gorm:"column:ipaddr;not null" json:"ipaddr"`                 // ip地址
	LoginLocation string         `gorm:"column:login_location;not null" json:"login_location"` // 归属地
	Browser       string         `gorm:"column:browser;not null" json:"browser"`               // 浏览器
	Os            string         `gorm:"column:os;not null" json:"os"`                         // 系统
	Platform      string         `gorm:"column:platform;not null" json:"platform"`             // 固件
	CreateBy      string         `gorm:"column:create_by;not null" json:"create_by"`           // 创建人
	UpdateBy      string         `gorm:"column:update_by;not null" json:"update_by"`           // 更新者
	Remark        string         `gorm:"column:remark;not null" json:"remark"`                 // 备注
	Msg           string         `gorm:"column:msg;not null" json:"msg"`                       // 消息
	LoginTime     time.Time      `gorm:"column:login_time" json:"login_time"`                  // 登录时间
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`                  // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`                  // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                  // 删除时间
}

// TableName LogLogin's table name
func (*LogLogin) TableName() string {
	return TableNameLogLogin
}
