// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameServerskusTbl = "serverskus_tbl"

// ServerskusTbl mapped from table <serverskus_tbl>
type ServerskusTbl struct {
	CreatedAt            time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt            time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion        int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt            gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted              bool           `gorm:"column:deleted;not null" json:"deleted"`
	ID                   string         `gorm:"column:id;primaryKey" json:"id"`
	Description          string         `gorm:"column:description" json:"description"`
	IsEmulated           bool           `gorm:"column:is_emulated;not null" json:"is_emulated"`
	Name                 string         `gorm:"column:name;not null" json:"name"`
	Status               string         `gorm:"column:status;not null;default:init" json:"status"`
	Progress             float32        `gorm:"column:progress;default:100" json:"progress"`
	Enabled              bool           `gorm:"column:enabled" json:"enabled"`
	ExternalID           string         `gorm:"column:external_id" json:"external_id"`
	ImportedAt           time.Time      `gorm:"column:imported_at" json:"imported_at"`
	Source               string         `gorm:"column:source" json:"source"`
	CloudregionID        string         `gorm:"column:cloudregion_id;not null;default:default" json:"cloudregion_id"`
	ZoneID               string         `gorm:"column:zone_id" json:"zone_id"`
	InstanceTypeFamily   string         `gorm:"column:instance_type_family" json:"instance_type_family"`
	InstanceTypeCategory string         `gorm:"column:instance_type_category" json:"instance_type_category"`
	LocalCategory        string         `gorm:"column:local_category" json:"local_category"`
	PrepaidStatus        string         `gorm:"column:prepaid_status;default:available" json:"prepaid_status"`
	PostpaidStatus       string         `gorm:"column:postpaid_status;default:available" json:"postpaid_status"`
	CPUArch              string         `gorm:"column:cpu_arch" json:"cpu_arch"`
	CPUCoreCount         int32          `gorm:"column:cpu_core_count;not null" json:"cpu_core_count"`
	MemorySizeMb         int32          `gorm:"column:memory_size_mb;not null" json:"memory_size_mb"`
	OsName               string         `gorm:"column:os_name;default:Any" json:"os_name"`
	SysDiskResizable     bool           `gorm:"column:sys_disk_resizable;default:1" json:"sys_disk_resizable"`
	SysDiskType          string         `gorm:"column:sys_disk_type" json:"sys_disk_type"`
	SysDiskMinSizeGb     int32          `gorm:"column:sys_disk_min_size_gb" json:"sys_disk_min_size_gb"`
	SysDiskMaxSizeGb     int32          `gorm:"column:sys_disk_max_size_gb" json:"sys_disk_max_size_gb"`
	AttachedDiskType     string         `gorm:"column:attached_disk_type" json:"attached_disk_type"`
	AttachedDiskSizeGb   int32          `gorm:"column:attached_disk_size_gb" json:"attached_disk_size_gb"`
	AttachedDiskCount    int32          `gorm:"column:attached_disk_count" json:"attached_disk_count"`
	DataDiskTypes        string         `gorm:"column:data_disk_types" json:"data_disk_types"`
	DataDiskMaxCount     int32          `gorm:"column:data_disk_max_count" json:"data_disk_max_count"`
	NicType              string         `gorm:"column:nic_type" json:"nic_type"`
	NicMaxCount          int32          `gorm:"column:nic_max_count;default:1" json:"nic_max_count"`
	GpuAttachable        bool           `gorm:"column:gpu_attachable;default:1" json:"gpu_attachable"`
	GpuSpec              string         `gorm:"column:gpu_spec" json:"gpu_spec"`
	GpuCount             string         `gorm:"column:gpu_count" json:"gpu_count"`
	GpuMaxCount          int32          `gorm:"column:gpu_max_count" json:"gpu_max_count"`
	Provider             string         `gorm:"column:provider;default:OneCloud" json:"provider"`
	Md5                  string         `gorm:"column:md5" json:"md5"`
}

// TableName ServerskusTbl's table name
func (*ServerskusTbl) TableName() string {
	return TableNameServerskusTbl
}
