// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysMenuBtn = "sys_menu_btns"

// SysMenuBtn mapped from table <sys_menu_btns>
type SysMenuBtn struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	MenuID int64  `gorm:"column:menu_id;not null" json:"menu_id"`            // 菜单ID
	Name   string `gorm:"column:name;not null" json:"name"`                  // 按钮关键key
	Desc   string `gorm:"column:desc;not null" json:"desc"`                  // 按钮描述
}

// TableName SysMenuBtn's table name
func (*SysMenuBtn) TableName() string {
	return TableNameSysMenuBtn
}
