// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysDiscovery = "sys_discovery"

// SysDiscovery mapped from table <sys_discovery>
type SysDiscovery struct {
	ID      int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name    string `gorm:"column:name" json:"name"`               // 名称
	Picture string `gorm:"column:picture" json:"picture"`         // 发现页图片
	Rank    int32  `gorm:"column:rank;default:1" json:"rank"`     // 排序
	Link    string `gorm:"column:link" json:"link"`               // 发现页链接
	Status  int32  `gorm:"column:status;default:1" json:"status"` // 发现页状态, 1-正常，2-异常
}

// TableName SysDiscovery's table name
func (*SysDiscovery) TableName() string {
	return TableNameSysDiscovery
}
