// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysJob = "sys_jobs"

// SysJob mapped from table <sys_jobs>
type SysJob struct {
	ID             int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	JobName        string         `gorm:"column:job_name;not null" json:"job_name"`          // 任务名称
	JobGroup       string         `gorm:"column:job_group" json:"job_group"`                 // 任务组
	JobType        int32          `gorm:"column:job_type" json:"job_type"`                   // 任务类型
	CronExpression string         `gorm:"column:cron_expression" json:"cron_expression"`     // cron表达式
	InvokeTarget   string         `gorm:"column:invoke_target" json:"invoke_target"`         // 调用目标
	Args           string         `gorm:"column:args" json:"args"`                           // 目标参数
	MisfirePolicy  int32          `gorm:"column:misfire_policy" json:"misfire_policy"`       // 执行策略
	Concurrent     int32          `gorm:"column:concurrent;default:2" json:"concurrent"`     // 是否并发 1=是 2=否
	Status         int32          `gorm:"column:status;default:1" json:"status"`             // 1=正常 2=异常
	EntryID        int32          `gorm:"column:entry_id" json:"entry_id"`                   // job启动时返回的id
	CreateBy       string         `gorm:"column:create_by" json:"create_by"`                 // 创建人
	UpdateBy       string         `gorm:"column:update_by" json:"update_by"`                 // 更新者
	CreatedAt      time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
}

// TableName SysJob's table name
func (*SysJob) TableName() string {
	return TableNameSysJob
}
