// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRole = "sys_roles"

// SysRole mapped from table <sys_roles>
type SysRole struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`      // 主键id
	ParentID      int64          `gorm:"column:parent_id;not null" json:"parent_id"`             // 父角色ID
	RoleName      string         `gorm:"column:role_name;not null" json:"role_name"`             // 角色名称
	Status        int32          `gorm:"column:status;not null;default:1" json:"status"`         // 1=正常 2=异常
	RoleKey       string         `gorm:"column:role_key;not null" json:"role_key"`               // 角色代码
	DataScope     int32          `gorm:"column:data_scope;not null;default:1" json:"data_scope"` // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
	RoleSort      int32          `gorm:"column:role_sort;not null" json:"role_sort"`             // 角色排序
	DefaultRouter string         `gorm:"column:default_router;not null" json:"default_router"`   // 默认菜单
	Remark        string         `gorm:"column:remark;not null" json:"remark"`                   // 备注
	CreateBy      string         `gorm:"column:create_by;not null" json:"create_by"`             // 创建人
	UpdateBy      string         `gorm:"column:update_by;not null" json:"update_by"`             // 更新人
	CreatedAt     time.Time      `gorm:"column:created_at" json:"created_at"`                    // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at" json:"updated_at"`                    // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                    // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
