// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictDatum = "sys_dict_data"

// SysDictDatum mapped from table <sys_dict_data>
type SysDictDatum struct {
	DictCode   int64     `gorm:"column:dict_code;primaryKey;autoIncrement:true" json:"dict_code"`
	DictSort   int32     `gorm:"column:dict_sort" json:"dict_sort"`   // 排序
	DictLabel  string    `gorm:"column:dict_label" json:"dict_label"` // 标签
	DictValue  string    `gorm:"column:dict_value" json:"dict_value"` // 值
	DictType   string    `gorm:"column:dict_type" json:"dict_type"`   // 字典类型
	Status     int32     `gorm:"column:status" json:"status"`         // 状态（0正常 1停用）
	CSSClass   string    `gorm:"column:css_class" json:"css_class"`   // CssClass
	ListClass  string    `gorm:"column:list_class" json:"list_class"` // ListClass
	IsDefault  string    `gorm:"column:is_default" json:"is_default"` // IsDefault
	CreateBy   string    `gorm:"column:create_by" json:"create_by"`
	UpdateBy   string    `gorm:"column:update_by" json:"update_by"`
	Remark     string    `gorm:"column:remark" json:"remark"` // 备注
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName SysDictDatum's table name
func (*SysDictDatum) TableName() string {
	return TableNameSysDictDatum
}
