// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDictType = "sys_dict_types"

// SysDictType mapped from table <sys_dict_types>
type SysDictType struct {
	DictID     int64     `gorm:"column:dict_id;primaryKey;autoIncrement:true" json:"dict_id"`
	DictName   string    `gorm:"column:dict_name" json:"dict_name"` // 名称
	DictType   string    `gorm:"column:dict_type" json:"dict_type"` // 类型
	Status     int32     `gorm:"column:status" json:"status"`       // 状态
	CreateBy   string    `gorm:"column:create_by" json:"create_by"`
	UpdateBy   string    `gorm:"column:update_by" json:"update_by"`
	Remark     string    `gorm:"column:remark" json:"remark"` // 备注
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time" json:"delete_time"`
}

// TableName SysDictType's table name
func (*SysDictType) TableName() string {
	return TableNameSysDictType
}
