// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleMenu = "sys_role_menus"

// SysRoleMenu mapped from table <sys_role_menus>
type SysRoleMenu struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	RoleID   int64  `gorm:"column:role_id;not null" json:"role_id"`            // 角色id
	MenuID   int64  `gorm:"column:menu_id;not null" json:"menu_id"`            // 菜单id
	RoleName string `gorm:"column:role_name;not null" json:"role_name"`        // 角色名称
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
