// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysPost = "sys_posts"

// SysPost mapped from table <sys_posts>
type SysPost struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	PostName  string         `gorm:"column:post_name;not null" json:"post_name"`        // 岗位名称
	PostCode  string         `gorm:"column:post_code;not null" json:"post_code"`        // 岗位代码
	Sort      int32          `gorm:"column:sort;not null" json:"sort"`                  // 岗位排序
	Status    int32          `gorm:"column:status;not null;default:1" json:"status"`    // 状态 1=正常 2=冻结
	Remark    string         `gorm:"column:remark;not null" json:"remark"`              // 描述
	CreateBy  string         `gorm:"column:create_by;not null" json:"create_by"`        // 创建人
	UpdateBy  string         `gorm:"column:update_by;not null" json:"update_by"`        // 修改人
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`               // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`               // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`               // 删除时间
}

// TableName SysPost's table name
func (*SysPost) TableName() string {
	return TableNameSysPost
}
