// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysMenu = "sys_menus"

// SysMenu mapped from table <sys_menus>
type SysMenu struct {
	ID         int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	MenuName   string         `gorm:"column:menu_name;not null" json:"menu_name"`             // 菜单名称
	Title      string         `gorm:"column:title;not null" json:"title"`                     // 附加属性
	ParentID   int64          `gorm:"column:parent_id;not null" json:"parent_id"`             // 父级菜单id
	Sort       int32          `gorm:"column:sort;not null" json:"sort"`                       // 排序
	Icon       string         `gorm:"column:icon;not null" json:"icon"`                       // 菜单图标
	Path       string         `gorm:"column:path;not null" json:"path"`                       // 路由地址
	Component  string         `gorm:"column:component;not null" json:"component"`             // 组件路径
	IsIframe   int32          `gorm:"column:is_iframe;not null;default:2" json:"is_iframe"`   // 是否为内嵌 1=是 2=否
	Link       string         `gorm:"column:link;not null" json:"link"`                       // 超链接
	MenuType   string         `gorm:"column:menu_type;not null;default:1" json:"menu_type"`   // 菜单类型（1目录 2菜单 3按钮）
	Hidden     int32          `gorm:"column:hidden;not null;default:1" json:"hidden"`         // 显示状态（0显示 1隐藏）
	KeepAlive  int32          `gorm:"column:keep_alive;not null;default:1" json:"keep_alive"` // 是否缓存组件状态（1是 2否）
	IsAffix    int32          `gorm:"column:is_affix;not null;default:1" json:"is_affix"`     // 是否固定在 tagsView 栏上（1是 2否）
	Permission string         `gorm:"column:permission;not null" json:"permission"`           // 权限标识
	Status     int32          `gorm:"column:status;not null;default:1" json:"status"`         // 菜单状态 1=正常 2=停用
	CreateBy   string         `gorm:"column:create_by;not null" json:"create_by"`             // 创建人
	UpdateBy   string         `gorm:"column:update_by;not null" json:"update_by"`             // 更新人
	Remark     string         `gorm:"column:remark;not null" json:"remark"`                   // 备注
	CreatedAt  time.Time      `gorm:"column:created_at" json:"created_at"`                    // 创建时间
	UpdatedAt  time.Time      `gorm:"column:updated_at" json:"updated_at"`                    // 更新时间
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`                    // 删除时间
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
