// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleDept = "sys_role_depts"

// SysRoleDept mapped from table <sys_role_depts>
type SysRoleDept struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	RoleID int64 `gorm:"column:role_id;not null" json:"role_id"`            // 角色id
	DeptID int64 `gorm:"column:dept_id;not null" json:"dept_id"`            // 部门id
}

// TableName SysRoleDept's table name
func (*SysRoleDept) TableName() string {
	return TableNameSysRoleDept
}
