// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleBtn = "sys_role_btns"

// SysRoleBtn mapped from table <sys_role_btns>
type SysRoleBtn struct {
	ID     int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键id
	RoleID int64 `gorm:"column:role_id;not null" json:"role_id"`            // 角色ID
	MenuID int64 `gorm:"column:menu_id;not null" json:"menu_id"`            // 菜单ID
	BtnID  int64 `gorm:"column:btn_id;not null" json:"btn_id"`              // 菜单按钮ID
}

// TableName SysRoleBtn's table name
func (*SysRoleBtn) TableName() string {
	return TableNameSysRoleBtn
}
