// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameZonesTbl = "zones_tbl"

// ZonesTbl mapped from table <zones_tbl>
type ZonesTbl struct {
	CreatedAt     time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	UpdateVersion int32          `gorm:"column:update_version;not null" json:"update_version"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Deleted       bool           `gorm:"column:deleted;not null" json:"deleted"`
	ID            string         `gorm:"column:id;primaryKey" json:"id"`
	Description   string         `gorm:"column:description" json:"description"`
	IsEmulated    bool           `gorm:"column:is_emulated;not null" json:"is_emulated"`
	Name          string         `gorm:"column:name;not null" json:"name"`
	Status        string         `gorm:"column:status;not null;default:init" json:"status"`
	Progress      float32        `gorm:"column:progress;default:100" json:"progress"`
	ExternalID    string         `gorm:"column:external_id" json:"external_id"`
	ImportedAt    time.Time      `gorm:"column:imported_at" json:"imported_at"`
	Source        string         `gorm:"column:source" json:"source"`
	CloudregionID string         `gorm:"column:cloudregion_id;not null;default:default" json:"cloudregion_id"`
	Location      string         `gorm:"column:location" json:"location"`
	Contacts      string         `gorm:"column:contacts" json:"contacts"`
	NameCn        string         `gorm:"column:name_cn" json:"name_cn"`
	ManagerURI    string         `gorm:"column:manager_uri" json:"manager_uri"`
}

// TableName ZonesTbl's table name
func (*ZonesTbl) TableName() string {
	return TableNameZonesTbl
}
