scrape-configs:
  - job-name: pyroscope
    scrape-interval: 60s
    enabled-profiles: [cpu, mem, goroutines, mutex, block]
    static-configs:
      - application: my-pyroscope
        targets:
          - www.wslhost.com:8000
        labels:
          env: dev
